sudo: required

language: bash

services:
  - docker

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install -y qemu qemu-user-static

script:
  - make build-timer

cache:
  directories:
  - images/*.img