dist: xenial

sudo: required

language: bash

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install crossbuild-essential-armhf

script:
  - bash download.sh
  - sudo bash mount.sh
  - bash patch.sh
  - sudo bash build.sh

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: output/*.tar.bz2
  skip_cleanup: true
  on:
    branch: master